version: '3.0'

services:
  postgres: 
    container_name: study_db
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes: 
  postgres-data:
