name: msg

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
        repository: fga-eps-mds/2024.1-MeasureSoftGram-Action
        path: US005-Throughput
        githubToken: ${{ secrets.GITHUBTOKEN }} # Token do GitHub
        msgramServiceToken: ${{ secrets.MSGRAMSERVICETOKEN }} # Token para acessar o serviço MeasureSoftGram
        productName: "teste-eps" # Nome do produto
