name: msg

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: msg
      uses: fga-eps-mds/2024.1-MeasureSoftGram-Action@US005-Throughput
      with: 
        githubToken: ${{ secrets.GITHUBTOKEN }} # Token do GitHub
        msgramServiceToken: ${{ secrets.MSGRAMSERVICETOKEN }} # Token para acessar o serviço MeasureSoftGram
        productName: "Produto teste"
